<template>
  <div class="app-global-alert-wrapper">
    <div
      v-for="alert in alertList"
      :key="alert.id"
      class="app-global-alert"
      :class="{ 'slide-bottom': alert.isShown }"
    >
      <SAlert v-show="alert.isShown" :type="alert.type" @close="hide(alert.id)">
        {{ alert.message }}
      </SAlert>
    </div>
  </div>
</template>

<script>
import SAlert from '~/components/base/s-alert/s-alert.vue'
import useGlobalAlert from '~/application/global-alert'

export default {
  components: {
    SAlert,
  },
  setup() {
    const globalAlert = useGlobalAlert()

    return {
      alertList: globalAlert.getAlertState(),
      hide: globalAlert.hideAlert,
    }
  },
}
</script>

<style lang="scss">
.app-global-alert-wrapper {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  z-index: 2000;
}

.app-global-alert {
  width: 100%;
}

.slide-bottom {
  -webkit-animation: global-alert-slide-bottom 0.3s
    cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: global-alert-slide-bottom 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-3-10 17:10:38
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-bottom
 * ----------------------------------------
 */
@-webkit-keyframes global-alert-slide-bottom {
  0% {
    -webkit-transform: translateY(-150px);
    transform: translateY(-150px);
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
  }
}
@keyframes global-alert-slide-bottom {
  0% {
    -webkit-transform: translateY(-150px);
    transform: translateY(-150px);
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
  }
}
</style>
